# Generated by Django 4.2.3 on 2023-07-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=50)),
                ('profile_date_of_birth', models.DateField()),
                ('profile_image', models.CharField(max_length=100)),
            ],
        ),
    ]
