# Generated by Django 4.2.3 on 2023-08-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SketchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sketch_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
