# Generated by Django 4.2.3 on 2023-07-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chakemyself', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chakedb',
            name='age',
            field=models.CharField(default='', max_length=20),
        ),
    ]
