# Generated by Django 4.2.3 on 2023-07-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chakemyself', '0002_alter_chakedb_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='chakedb',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
