# Generated by Django 4.2.3 on 2023-07-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_products_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='products_views',
        ),
    ]
