# Generated by Django 4.2.3 on 2023-07-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_products_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='shop/imges'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_catagory',
            field=models.CharField(default='', max_length=30),
        ),
    ]
