# Generated by Django 4.2.3 on 2023-07-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_catagory_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='qrname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('second_name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='shop/qrimgs')),
            ],
        ),
    ]
