# Generated by Django 4.2.3 on 2023-07-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_qrname_image_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrname',
            name='image_information',
            field=models.CharField(default='', max_length=500),
        ),
    ]
