# Generated by Django 4.2.3 on 2023-07-25 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_qrname_image_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrname',
            name='datetime',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
